// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBuyApi.DataBase;

#nullable disable

namespace SmartBuyApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230805124705_added-metrics")]
    partial class addedmetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.FilterName", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Metric")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tbl_FilterNames");

                    b.HasData(
                        new
                        {
                            Id = "STV2OaUs3Ug",
                            CategoryId = "TipOdHHM-Sw",
                            Name = "GraphicCard",
                            PublicName = "Дискретна відеокарта"
                        },
                        new
                        {
                            Id = "fUVZ0s-Ih_j",
                            CategoryId = "TipOdHHM-Sw",
                            Name = "Processor",
                            PublicName = "Процесор"
                        },
                        new
                        {
                            Id = "Vn2HTHKfqRw",
                            CategoryId = "TipOdHHM-Sw",
                            Metric = "ГБ",
                            Name = "RAM",
                            PublicName = "Обсяг оперативної пам'яті"
                        },
                        new
                        {
                            Id = "3qzkZGJEIEy",
                            CategoryId = "Etn4MEcPF7H",
                            Metric = "мА·год",
                            Name = "BatteryCapacity",
                            PublicName = "Ємність акумулятора"
                        },
                        new
                        {
                            Id = "KJakzR3BERJ",
                            CategoryId = "Etn4MEcPF7H",
                            Metric = "\"",
                            Name = "DisplayDiagonal",
                            PublicName = "Діагональ екрана"
                        });
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.FilterValue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FilterNameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<string>("PublicValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StringValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilterNameId");

                    b.ToTable("tbl_FilterValues");

                    b.HasData(
                        new
                        {
                            Id = "1RusJ3mOvIq",
                            FilterNameId = "STV2OaUs3Ug",
                            MaxValue = 0.0,
                            MinValue = 0.0,
                            PublicValue = "GeForce RTX 3070",
                            StringValue = "RTX 3070"
                        },
                        new
                        {
                            Id = "WpQ4JHR5jHp",
                            FilterNameId = "STV2OaUs3Ug",
                            MaxValue = 0.0,
                            MinValue = 0.0,
                            PublicValue = "GeForce RTX 3060",
                            StringValue = "RTX 3060"
                        },
                        new
                        {
                            Id = "EIIvqGrSXpU",
                            FilterNameId = "STV2OaUs3Ug",
                            MaxValue = 0.0,
                            MinValue = 0.0,
                            PublicValue = "GeForce RTX 3050",
                            StringValue = "RTX 3050"
                        },
                        new
                        {
                            Id = "2zbX0yHqR-P",
                            FilterNameId = "fUVZ0s-Ih_j",
                            MaxValue = 0.0,
                            MinValue = 0.0,
                            PublicValue = "AMD Ryzen 7",
                            StringValue = "AMD Ryzen 7"
                        },
                        new
                        {
                            Id = "ja1PAZpfFmA",
                            FilterNameId = "fUVZ0s-Ih_j",
                            MaxValue = 0.0,
                            MinValue = 0.0,
                            PublicValue = "Intel Core i7",
                            StringValue = "Intel Core i7"
                        },
                        new
                        {
                            Id = "pOwkLFq7JiQ",
                            FilterNameId = "fUVZ0s-Ih_j",
                            MaxValue = 0.0,
                            MinValue = 0.0,
                            PublicValue = "Intel Core i5",
                            StringValue = "Intel Core i5"
                        },
                        new
                        {
                            Id = "dLDar3bpS1H",
                            FilterNameId = "Vn2HTHKfqRw",
                            MaxValue = 3.0,
                            MinValue = 0.20000000000000001,
                            PublicValue = "3 ГБ і менше"
                        },
                        new
                        {
                            Id = "h9D9t-9JMX_",
                            FilterNameId = "Vn2HTHKfqRw",
                            MaxValue = 4.0,
                            MinValue = 4.0,
                            PublicValue = "4 ГБ"
                        },
                        new
                        {
                            Id = "DbCTTn4sgmP",
                            FilterNameId = "Vn2HTHKfqRw",
                            MaxValue = 8.0,
                            MinValue = 6.0,
                            PublicValue = "6 - 8 ГБ"
                        },
                        new
                        {
                            Id = "kzc4zy7Hpc2",
                            FilterNameId = "Vn2HTHKfqRw",
                            MaxValue = 12.0,
                            MinValue = 10.0,
                            PublicValue = "10 - 12 ГБ"
                        },
                        new
                        {
                            Id = "rKFPG7i-HJ-",
                            FilterNameId = "Vn2HTHKfqRw",
                            MaxValue = 24.0,
                            MinValue = 16.0,
                            PublicValue = "16 - 24 ГБ"
                        },
                        new
                        {
                            Id = "xcTsS8a82TM",
                            FilterNameId = "3qzkZGJEIEy",
                            MaxValue = 3999.0,
                            MinValue = 3000.0,
                            PublicValue = "3000 - 3999 мА*год "
                        },
                        new
                        {
                            Id = "SsSX723SF7H",
                            FilterNameId = "3qzkZGJEIEy",
                            MaxValue = 4999.0,
                            MinValue = 4000.0,
                            PublicValue = "4000 - 4999 мА*год "
                        },
                        new
                        {
                            Id = "jSEjvUyPX-8",
                            FilterNameId = "KJakzR3BERJ",
                            MaxValue = 5.0,
                            MinValue = 4.5999999999999996,
                            PublicValue = "4.6\" - 5\""
                        },
                        new
                        {
                            Id = "Tt3p-H16vJY",
                            FilterNameId = "KJakzR3BERJ",
                            MaxValue = 5.5,
                            MinValue = 5.0099999999999998,
                            PublicValue = "5.01\" - 5.5\""
                        },
                        new
                        {
                            Id = "uIJRA05X5hf",
                            FilterNameId = "KJakzR3BERJ",
                            MaxValue = 6.0,
                            MinValue = 5.5,
                            PublicValue = "5.5\" - 6\""
                        });
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.GlobalCategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_GlobalCategories");

                    b.HasData(
                        new
                        {
                            Id = "G175130WxVT",
                            Name = "Смартфони та планшети"
                        },
                        new
                        {
                            Id = "dptakoxhIT3",
                            Name = "Комп’ютери та ноутбуки"
                        },
                        new
                        {
                            Id = "EQ48w1Wg16Q",
                            Name = "Фото та відео"
                        },
                        new
                        {
                            Id = "H9DkILQqQP4",
                            Name = "Аудіо"
                        },
                        new
                        {
                            Id = "Xd2JvkNGRiI",
                            Name = "Мультимедіа"
                        },
                        new
                        {
                            Id = "T7ADWrPfx_e",
                            Name = "Ігрова техніка"
                        },
                        new
                        {
                            Id = "7E4SxxsZsrK",
                            Name = "Побутова техніка"
                        },
                        new
                        {
                            Id = "OafTUgAVW-d",
                            Name = "Електронні гаджети"
                        },
                        new
                        {
                            Id = "zJoUiG-LVQi",
                            Name = "Електро-інструменти"
                        });
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.ImageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GlobalCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasFilter("[CategoryId] IS NOT NULL");

                    b.HasIndex("GlobalCategoryId")
                        .IsUnique()
                        .HasFilter("[GlobalCategoryId] IS NOT NULL");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = "urgh26qgwhq",
                            Name = "1_1.webp",
                            Priority = 1,
                            ProductId = "CMBQ8wHUFbP"
                        },
                        new
                        {
                            Id = "B72qFy2rpD-",
                            Name = "1_2.webp",
                            Priority = 2,
                            ProductId = "CMBQ8wHUFbP"
                        },
                        new
                        {
                            Id = "jbvJz_0KM0i",
                            Name = "1_3.webp",
                            Priority = 3,
                            ProductId = "CMBQ8wHUFbP"
                        },
                        new
                        {
                            Id = "iN--R78f_4F",
                            Name = "2_1.webp",
                            Priority = 1,
                            ProductId = "fPWf_wP9glL"
                        },
                        new
                        {
                            Id = "P3YGIqtsrlX",
                            Name = "2_2.webp",
                            Priority = 2,
                            ProductId = "fPWf_wP9glL"
                        },
                        new
                        {
                            Id = "2TzcEPgsmLB",
                            Name = "2_3.webp",
                            Priority = 3,
                            ProductId = "fPWf_wP9glL"
                        },
                        new
                        {
                            Id = "zNh2Hwhntnl",
                            Name = "3_1.webp",
                            Priority = 1,
                            ProductId = "6PUxRpn6eh1"
                        },
                        new
                        {
                            Id = "FCmD-UIu2HK",
                            Name = "3_2.webp",
                            Priority = 2,
                            ProductId = "6PUxRpn6eh1"
                        },
                        new
                        {
                            Id = "POZa1I8Ey61",
                            Name = "3_3.webp",
                            Priority = 3,
                            ProductId = "6PUxRpn6eh1"
                        },
                        new
                        {
                            Id = "h-LgoSOpBR5",
                            Name = "1_1.webp",
                            Priority = 1,
                            ProductId = "hweaWUQsEpP"
                        },
                        new
                        {
                            Id = "kNw5tkntl4C",
                            Name = "1_2.webp",
                            Priority = 2,
                            ProductId = "hweaWUQsEpP"
                        },
                        new
                        {
                            Id = "kVL6QMFS1J6",
                            Name = "1_3.webp",
                            Priority = 3,
                            ProductId = "hweaWUQsEpP"
                        },
                        new
                        {
                            Id = "V6A4_HrUsZB",
                            Name = "2_1.webp",
                            Priority = 1,
                            ProductId = "oAiUmX6r7mF"
                        },
                        new
                        {
                            Id = "CNO3LURB-1Z",
                            Name = "2_2.webp",
                            Priority = 2,
                            ProductId = "oAiUmX6r7mF"
                        },
                        new
                        {
                            Id = "WGb2_sDk1r_",
                            Name = "2_3.webp",
                            Priority = 3,
                            ProductId = "oAiUmX6r7mF"
                        },
                        new
                        {
                            Id = "piyl4JV9fu_",
                            Name = "3_1.webp",
                            Priority = 1,
                            ProductId = "9rjmfYNo75k"
                        },
                        new
                        {
                            Id = "N8qGGYdFSXS",
                            Name = "3_2.webp",
                            Priority = 2,
                            ProductId = "9rjmfYNo75k"
                        },
                        new
                        {
                            Id = "yh15A3QMUvt",
                            Name = "3_3.webp",
                            Priority = 3,
                            ProductId = "9rjmfYNo75k"
                        },
                        new
                        {
                            Id = "NHyoONFjqMN",
                            Name = "1_1.webp",
                            Priority = 1,
                            ProductId = "CsJpKZcgIFP"
                        },
                        new
                        {
                            Id = "0yKMshwj9NU",
                            Name = "1_2.webp",
                            Priority = 2,
                            ProductId = "CsJpKZcgIFP"
                        },
                        new
                        {
                            Id = "AeLRNBqOXoa",
                            Name = "1_3.webp",
                            Priority = 3,
                            ProductId = "CsJpKZcgIFP"
                        },
                        new
                        {
                            Id = "tAoK5CRjbO5",
                            Name = "2_1.webp",
                            Priority = 1,
                            ProductId = "k53D4B3EJTQ"
                        },
                        new
                        {
                            Id = "-LxfBDIViC6",
                            Name = "2_2.webp",
                            Priority = 2,
                            ProductId = "k53D4B3EJTQ"
                        },
                        new
                        {
                            Id = "T80vi_q1_kL",
                            Name = "2_3.webp",
                            Priority = 3,
                            ProductId = "k53D4B3EJTQ"
                        },
                        new
                        {
                            Id = "hOaHNQ0VoLB",
                            Name = "3_1.webp",
                            Priority = 1,
                            ProductId = "amXu5kFrlKj"
                        },
                        new
                        {
                            Id = "orfJcC9PGI-",
                            Name = "3_2.webp",
                            Priority = 2,
                            ProductId = "amXu5kFrlKj"
                        },
                        new
                        {
                            Id = "YK_JGYHHtKE",
                            Name = "3_3.webp",
                            Priority = 3,
                            ProductId = "amXu5kFrlKj"
                        },
                        new
                        {
                            Id = "htCRYmKCjO-",
                            Name = "1_1.webp",
                            Priority = 1,
                            ProductId = "6sbQHsctdc2"
                        },
                        new
                        {
                            Id = "-3avYR4X0X0",
                            Name = "1_2.webp",
                            Priority = 2,
                            ProductId = "6sbQHsctdc2"
                        },
                        new
                        {
                            Id = "WIw4MjEoUNF",
                            Name = "1_3.webp",
                            Priority = 3,
                            ProductId = "6sbQHsctdc2"
                        },
                        new
                        {
                            Id = "uJv5I73fqQr",
                            Name = "3_1.webp",
                            Priority = 1,
                            ProductId = "yU9tdyFSq8k"
                        },
                        new
                        {
                            Id = "5wYOT1deuyc",
                            Name = "3_2.webp",
                            Priority = 2,
                            ProductId = "yU9tdyFSq8k"
                        },
                        new
                        {
                            Id = "m2K893yfU2O",
                            Name = "3_3.webp",
                            Priority = 3,
                            ProductId = "yU9tdyFSq8k"
                        },
                        new
                        {
                            Id = "J9QZh9mYX3o",
                            Name = "4_1.webp",
                            Priority = 1,
                            ProductId = "n-FsUQx3TT4"
                        },
                        new
                        {
                            Id = "hHA8jJoHx08",
                            Name = "4_2.webp",
                            Priority = 2,
                            ProductId = "n-FsUQx3TT4"
                        },
                        new
                        {
                            Id = "Ytk-YTP_9oI",
                            Name = "4_3.webp",
                            Priority = 3,
                            ProductId = "n-FsUQx3TT4"
                        },
                        new
                        {
                            Id = "ZzmP6jK1tfb",
                            Name = "5_1.webp",
                            Priority = 1,
                            ProductId = "hhH1lAyeC4G"
                        },
                        new
                        {
                            Id = "QHKXu1EyNB3",
                            Name = "5_2.webp",
                            Priority = 2,
                            ProductId = "hhH1lAyeC4G"
                        },
                        new
                        {
                            Id = "o8Gazw49GkO",
                            Name = "5_3.webp",
                            Priority = 3,
                            ProductId = "hhH1lAyeC4G"
                        },
                        new
                        {
                            Id = "uYovHGqxFRd",
                            Name = "6_1.webp",
                            Priority = 1,
                            ProductId = "pHPOffxiMm2"
                        },
                        new
                        {
                            Id = "r-E3ARazcVy",
                            Name = "6_2.webp",
                            Priority = 2,
                            ProductId = "pHPOffxiMm2"
                        },
                        new
                        {
                            Id = "4zd75_v5582",
                            Name = "6_3.webp",
                            Priority = 3,
                            ProductId = "pHPOffxiMm2"
                        },
                        new
                        {
                            Id = "cEkFEaMAyq5",
                            Name = "3_1.webp",
                            Priority = 1,
                            ProductId = "1Rl1j1s3qpG"
                        },
                        new
                        {
                            Id = "62bPHgCV5LQ",
                            Name = "3_2.webp",
                            Priority = 2,
                            ProductId = "1Rl1j1s3qpG"
                        },
                        new
                        {
                            Id = "yS-bqQqFDXf",
                            Name = "3_3.webp",
                            Priority = 3,
                            ProductId = "1Rl1j1s3qpG"
                        },
                        new
                        {
                            Id = "Z3AuQB-K33D",
                            Name = "4_1.webp",
                            Priority = 1,
                            ProductId = "053ogias15a"
                        },
                        new
                        {
                            Id = "jSlojkT5Sgt",
                            Name = "4_2.webp",
                            Priority = 2,
                            ProductId = "053ogias15a"
                        },
                        new
                        {
                            Id = "0B-0M7wPqsJ",
                            Name = "4_3.webp",
                            Priority = 3,
                            ProductId = "053ogias15a"
                        },
                        new
                        {
                            Id = "JHr3_2B9lGR",
                            Name = "5_1.webp",
                            Priority = 1,
                            ProductId = "1LXieYtc4ey"
                        },
                        new
                        {
                            Id = "Y-M8L8xZYor",
                            Name = "5_2.webp",
                            Priority = 2,
                            ProductId = "1LXieYtc4ey"
                        },
                        new
                        {
                            Id = "IphlcbVelIj",
                            Name = "5_3.webp",
                            Priority = 3,
                            ProductId = "1LXieYtc4ey"
                        },
                        new
                        {
                            Id = "OOFox6fFkWG",
                            Name = "6_1.webp",
                            Priority = 1,
                            ProductId = "KNizPZuCG8y"
                        },
                        new
                        {
                            Id = "BVqWu3xrWxA",
                            Name = "6_2.webp",
                            Priority = 2,
                            ProductId = "KNizPZuCG8y"
                        },
                        new
                        {
                            Id = "RsUAL_GYBIm",
                            Name = "6_3.webp",
                            Priority = 3,
                            ProductId = "KNizPZuCG8y"
                        },
                        new
                        {
                            Id = "kftaUPc0peJ",
                            Name = "3_1.webp",
                            Priority = 1,
                            ProductId = "_fZUZaNtclq"
                        },
                        new
                        {
                            Id = "wy_jT-Tx5L6",
                            Name = "3_2.webp",
                            Priority = 2,
                            ProductId = "_fZUZaNtclq"
                        },
                        new
                        {
                            Id = "x1OyBSRoUdp",
                            Name = "3_3.webp",
                            Priority = 3,
                            ProductId = "_fZUZaNtclq"
                        },
                        new
                        {
                            Id = "Q6Kj1ru8N_O",
                            Name = "4_1.webp",
                            Priority = 1,
                            ProductId = "8VFU6-yND0B"
                        },
                        new
                        {
                            Id = "6C6BmfMJjGR",
                            Name = "4_2.webp",
                            Priority = 2,
                            ProductId = "8VFU6-yND0B"
                        },
                        new
                        {
                            Id = "MlMbcNpSW4J",
                            Name = "4_3.webp",
                            Priority = 3,
                            ProductId = "8VFU6-yND0B"
                        },
                        new
                        {
                            Id = "iYJEYhZAaJb",
                            Name = "5_1.webp",
                            Priority = 1,
                            ProductId = "YGE3QJoplSt"
                        },
                        new
                        {
                            Id = "TEsi9RGyFZ6",
                            Name = "5_2.webp",
                            Priority = 2,
                            ProductId = "YGE3QJoplSt"
                        },
                        new
                        {
                            Id = "6c9jRRtj3uk",
                            Name = "5_3.webp",
                            Priority = 3,
                            ProductId = "YGE3QJoplSt"
                        },
                        new
                        {
                            Id = "5fmMxqZVKws",
                            Name = "6_1.webp",
                            Priority = 1,
                            ProductId = "Iik7q__BtH-"
                        },
                        new
                        {
                            Id = "f6_LxrCPJsx",
                            Name = "6_2.webp",
                            Priority = 2,
                            ProductId = "Iik7q__BtH-"
                        },
                        new
                        {
                            Id = "qZPLQfkPA37",
                            Name = "6_3.webp",
                            Priority = 3,
                            ProductId = "Iik7q__BtH-"
                        },
                        new
                        {
                            Id = "NEHoWVASE4p",
                            CategoryId = "TipOdHHM-Sw",
                            GlobalCategoryId = "dptakoxhIT3",
                            Name = "laptops.webp",
                            Priority = 1
                        },
                        new
                        {
                            Id = "SoSqOufc3J4",
                            GlobalCategoryId = "G175130WxVT",
                            Name = "tablets.webp",
                            Priority = 1
                        },
                        new
                        {
                            Id = "-PcrABfMXng",
                            CategoryId = "Etn4MEcPF7H",
                            Name = "telephones.webp",
                            Priority = 1
                        });
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmartUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SmartUserId");

                    b.ToTable("tbl_Tokens");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.ReviewEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Advantages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Disadvantages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ProductId");

                    b.ToTable("tbl_Reviews");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Tables.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("GlobalCategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalCategoryId");

                    b.ToTable("tbl_Categories");

                    b.HasData(
                        new
                        {
                            Id = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7282),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            GlobalCategoryId = "dptakoxhIT3",
                            IsDelete = false,
                            Name = "Ноутбуки, ультрабуки та мінібуки"
                        },
                        new
                        {
                            Id = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7336),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            GlobalCategoryId = "G175130WxVT",
                            IsDelete = false,
                            Name = "Смартфони"
                        },
                        new
                        {
                            Id = "2Z177E-xDUQ",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7341),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            GlobalCategoryId = "G175130WxVT",
                            IsDelete = false,
                            Name = "Планшети"
                        },
                        new
                        {
                            Id = "mhibU-kKVH1",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7345),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            GlobalCategoryId = "G175130WxVT",
                            IsDelete = false,
                            Name = "Аксесуари для смартфонів і планшетів"
                        },
                        new
                        {
                            Id = "73TPXfy6Wug",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7349),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            GlobalCategoryId = "dptakoxhIT3",
                            IsDelete = false,
                            Name = "настільні ПК"
                        },
                        new
                        {
                            Id = "qYOlqV3HC9W",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7380),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "description",
                            GlobalCategoryId = "dptakoxhIT3",
                            IsDelete = false,
                            Name = "монітори"
                        });
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Tables.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Dicount")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tbl_Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductEntity");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "QdZrDAqzEFN",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7429),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "test",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "ПК Х123434",
                            Price = 436765,
                            ShortDescription = "figna"
                        },
                        new
                        {
                            Id = "ncXiz4DS2Ta",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7436),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ми представляємо вам найпотужнішу, саму оснащену, ударотривкий та найефективнішу версію смартфона 2021 року від румунської компанії iHunt .",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "iHunt Titan P13000 PRO 2021",
                            Price = 13940,
                            ShortDescription = "figna"
                        },
                        new
                        {
                            Id = "3E-DajpRoDz",
                            CategoryId = "2Z177E-xDUQ",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7441),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Холодильники з системою NeoFrost ",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "BEKO CNA295K20XP",
                            Price = 10999,
                            ShortDescription = "figna"
                        },
                        new
                        {
                            Id = "Bk5SWIMtsem",
                            CategoryId = "mhibU-kKVH1",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7446),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ланцюгова пила Bosch UniversalChain ",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Bosch UniversalChain 40",
                            Price = 3958,
                            ShortDescription = "figna"
                        },
                        new
                        {
                            Id = "XVQ9pIdZXCi",
                            CategoryId = "73TPXfy6Wug",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7450),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Велосипед Champion Spark 29 ",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Champion Spark 29 19.5 Black-neon yellow-white",
                            Price = 5460,
                            ShortDescription = "figna"
                        },
                        new
                        {
                            Id = "UAF1RKE42OA",
                            CategoryId = "qYOlqV3HC9W",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Utc).AddTicks(7453),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ВНабір паперу офісного Zoom Stora Enso А4 80 г/м2 клас С + 5 пачок по 500 аркушів Біла ",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Zoom Stora Enso А4 80 г/м2 клас С + 5 пачок по 500 аркушів Біла",
                            Price = 1199,
                            ShortDescription = "figna"
                        });
                });

            modelBuilder.Entity("SmartBuyApi.DataBase.Tables.Adress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("House")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_Adresses", (string)null);
                });

            modelBuilder.Entity("SmartBuyApi.DataBase.Tables.SmartUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("tbl_Users", (string)null);
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.SpecializedProducts.Laptop", b =>
                {
                    b.HasBaseType("SmartBuyApi.Data.DataBase.Tables.ProductEntity");

                    b.Property<string>("GraphicCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RAM")
                        .HasColumnType("float");

                    b.ToTable("tbl_Products");

                    b.HasDiscriminator().HasValue("Laptop");

                    b.HasData(
                        new
                        {
                            Id = "CMBQ8wHUFbP",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7742),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук Acer Aspire 7 A715-42G-R3EZ (NH.QBFEU.00C) Charcoal Black",
                            Price = 28999,
                            ShortDescription = "Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.15 кг / чорний",
                            GraphicCard = "RTX 3070",
                            Processor = "Intel Core i7",
                            RAM = 7.0
                        },
                        new
                        {
                            Id = "fPWf_wP9glL",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7746),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук Acer22222 Aspire 7 A715-42G-R3EZ (NH.QBFEU.00C) Charcoal Black",
                            Price = 28999,
                            ShortDescription = "Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.15 кг / чорний",
                            GraphicCard = "RTX 3050",
                            Processor = "Intel Core i5",
                            RAM = 11.0
                        },
                        new
                        {
                            Id = "6PUxRpn6eh1",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7748),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук Acer333333 Aspire 7 A715-42G-R3EZ (NH.QBFEU.00C) Charcoal Black",
                            Price = 28999,
                            ShortDescription = "Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.15 кг / чорний",
                            GraphicCard = "RTX 3070",
                            Processor = "Intel Core i7",
                            RAM = 10.0
                        },
                        new
                        {
                            Id = "hweaWUQsEpP",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7750),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук Acer44444444444 Aspire 7 A715-42G-R3EZ (NH.QBFEU.00C) Charcoal Black",
                            Price = 28999,
                            ShortDescription = "Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.15 кг / чорний",
                            GraphicCard = "RTX 3060",
                            Processor = "AMD Ryzen 7",
                            RAM = 12.0
                        },
                        new
                        {
                            Id = "oAiUmX6r7mF",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7752),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук Acer Aspire 7 A715-42G-R3EZ (NH.QBFEU.00C) Charcoal Black",
                            Price = 28999,
                            ShortDescription = "Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.15 кг / чорний",
                            GraphicCard = "RTX 3050",
                            Processor = "AMD Ryzen 7",
                            RAM = 4.0
                        },
                        new
                        {
                            Id = "9rjmfYNo75k",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7754),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук Acer Aspire 7 A715-42G-R3EZ (NH.QBFEU.00C) Charcoal Black",
                            Price = 28999,
                            ShortDescription = "Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.15 кг / чорний",
                            GraphicCard = "RTX 3060",
                            Processor = "Intel Core i7",
                            RAM = 4.0
                        },
                        new
                        {
                            Id = "CsJpKZcgIFP",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7756),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук HP Pavilion 15-cs3006ur Natural Silver",
                            Price = 23999,
                            ShortDescription = "Екран 15.6\" IPS (1920x1080) Full HD, матовий / Intel Core i5-1135G7 (2.4 - 4.2 ГГц) / RAM 8 ГБ / SSD 256 ГБ / Intel Iris Xe Graphics / без ОД / Wi-Fi / Bluetooth / веб-камера / Windows 11 Home / 1.75 кг / сріблястий",
                            GraphicCard = "Intel Iris Xe Graphics",
                            Processor = "Intel Core i5",
                            RAM = 16.0
                        },
                        new
                        {
                            Id = "k53D4B3EJTQ",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7758),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук Lenovo IdeaPad 5 Pro 16ACH6",
                            Price = 29999,
                            ShortDescription = "Екран 16\" IPS (2560x1600) WQXGA, матовий / AMD Ryzen 7 5800H (3.2 - 4.4 ГГц) / RAM 16 ГБ / SSD 512 ГБ / NVIDIA GeForce RTX 3050, 4 ГБ / без ОД / Wi-Fi / Bluetooth / веб-камера / Windows 11 Home / 2.2 кг / сірий",
                            GraphicCard = "RTX 3050",
                            Processor = "AMD Ryzen 7",
                            RAM = 2.0
                        },
                        new
                        {
                            Id = "amXu5kFrlKj",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7760),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук Acer Aspire 7 A715-42G-R3EZ (NH.QBFEU.00C) Charcoal Black",
                            Price = 28999,
                            ShortDescription = "Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 8 ГБ / SSD 128 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.15 кг / чорний",
                            GraphicCard = "RTX 3070",
                            Processor = "Intel Core i7",
                            RAM = 3.0
                        },
                        new
                        {
                            Id = "6sbQHsctdc2",
                            CategoryId = "TipOdHHM-Sw",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7762),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Ноутбук Acer Aspire 7 A715-42G-R3EZ (NH.QBFEU.00C) Charcoal Black",
                            Price = 28999,
                            ShortDescription = "Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.15 кг / чорний",
                            GraphicCard = "RTX 3060",
                            Processor = "Intel Core i5",
                            RAM = 1.0
                        });
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.SpecializedProducts.Telephone", b =>
                {
                    b.HasBaseType("SmartBuyApi.Data.DataBase.Tables.ProductEntity");

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("int");

                    b.Property<double>("DisplayDiagonal")
                        .HasColumnType("float");

                    b.ToTable("tbl_Products");

                    b.HasDiscriminator().HasValue("Telephone");

                    b.HasData(
                        new
                        {
                            Id = "yU9tdyFSq8k",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7786),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобільний телефон Apple iPhone 14 Pro Max 128GB Deep Purple",
                            Price = 54999,
                            ShortDescription = "Екран (6.7\", OLED (Super Retina XDR), 2796x1290) / Apple A16 Bionic / основна квадро-камера: 48 Мп + 12 Мп + 12 Мп + 12 Мп, фронтальна камера: 12 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / iOS 16",
                            BatteryCapacity = 3100,
                            DisplayDiagonal = 6.4000000000000004
                        },
                        new
                        {
                            Id = "n-FsUQx3TT4",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7790),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобільний телефон Apple i111",
                            Price = 54999,
                            ShortDescription = "Екран (6.7\", OLED (Super Retina XDR), 2796x1290) / Apple A16 Bionic / основна квадро-камера: 48 Мп + 12 Мп + 12 Мп + 12 Мп, фронтальна камера: 12 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / iOS 16",
                            BatteryCapacity = 4100,
                            DisplayDiagonal = 5.5999999999999996
                        },
                        new
                        {
                            Id = "hhH1lAyeC4G",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7887),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобільний телефон Apple i222",
                            Price = 54999,
                            ShortDescription = "Екран (6.7\", OLED (Super Retina XDR), 2796x1290) / Apple A16 Bionic / основна квадро-камера: 48 Мп + 12 Мп + 12 Мп + 12 Мп, фронтальна камера: 12 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / iOS 16",
                            BatteryCapacity = 3600,
                            DisplayDiagonal = 5.5
                        },
                        new
                        {
                            Id = "pHPOffxiMm2",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7890),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобільний телефон Apple i333313",
                            Price = 54999,
                            ShortDescription = "Екран (6.7\", OLED (Super Retina XDR), 2796x1290) / Apple A16 Bionic / основна квадро-камера: 48 Мп + 12 Мп + 12 Мп + 12 Мп, фронтальна камера: 12 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / iOS 16",
                            BatteryCapacity = 3900,
                            DisplayDiagonal = 5.2000000000000002
                        },
                        new
                        {
                            Id = "1Rl1j1s3qpG",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7892),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мо4444444 4414 Pro Max 128GB Deep Purple",
                            Price = 54999,
                            ShortDescription = "Екран (6.7\", OLED (Super Retina XDR), 2796x1290) / Apple A16 Bionic / основна квадро-камера: 48 Мп + 12 Мп + 12 Мп + 12 Мп, фронтальна камера: 12 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / iOS 16",
                            BatteryCapacity = 4800,
                            DisplayDiagonal = 8.4000000000000004
                        },
                        new
                        {
                            Id = "053ogias15a",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7894),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "М55555555 Deep Purple",
                            Price = 54999,
                            ShortDescription = "Екран (6.7\", OLED (Super Retina XDR), 2796x1290) / Apple A16 Bionic / основна квадро-камера: 48 Мп + 12 Мп + 12 Мп + 12 Мп, фронтальна камера: 12 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / iOS 16",
                            BatteryCapacity = 4900,
                            DisplayDiagonal = 6.2999999999999998
                        },
                        new
                        {
                            Id = "1LXieYtc4ey",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7896),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобільний 66666666B Deep Purple",
                            Price = 54999,
                            ShortDescription = "Екран (6.7\", OLED (Super Retina XDR), 2796x1290) / Apple A16 Bionic / основна квадро-камера: 48 Мп + 12 Мп + 12 Мп + 12 Мп, фронтальна камера: 12 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / iOS 16",
                            BatteryCapacity = 4200,
                            DisplayDiagonal = 5.0999999999999996
                        },
                        new
                        {
                            Id = "KNizPZuCG8y",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7898),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобіл77777777 28GB Deep Purple",
                            Price = 54999,
                            ShortDescription = "Екран (6.7\", OLED (Super Retina XDR), 2796x1290) / Apple A16 Bionic / основна квадро-камера: 48 Мп + 12 Мп + 12 Мп + 12 Мп, фронтальна камера: 12 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / iOS 16",
                            BatteryCapacity = 4600,
                            DisplayDiagonal = 4.9000000000000004
                        },
                        new
                        {
                            Id = "_fZUZaNtclq",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7901),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобільний телефон Google Pixel 7",
                            Price = 32999,
                            ShortDescription = "Екран (6.2\", OLED, 2400x1080) / Qualcomm Snapdragon 778G / основна камера: 64 Мп + 16 Мп + 12 Мп, фронтальна камера: 12 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / eSIM / Android 12",
                            BatteryCapacity = 4500,
                            DisplayDiagonal = 6.2000000000000002
                        },
                        new
                        {
                            Id = "8VFU6-yND0B",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7903),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобільний телефон Sony Xperia 1 IV",
                            Price = 74999,
                            ShortDescription = "Екран (6.5\", OLED, 3840x1644) / Qualcomm Snapdragon 888 / основна камера: 64 Мп + 16 Мп + 12 Мп, фронтальна камера: 10 Мп / 256 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / Android 12",
                            BatteryCapacity = 5000,
                            DisplayDiagonal = 6.5
                        },
                        new
                        {
                            Id = "YGE3QJoplSt",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7905),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобільний телефон Xiaomi Mi 12",
                            Price = 39999,
                            ShortDescription = "Екран (6.81\", OLED, 3200x1440) / Qualcomm Snapdragon 8 Gen 1 / основна квадро-камера: 50 Мп + 12 Мп + 8 Мп + 2 Мп, фронтальна камера: 32 Мп / 256 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Dual SIM / Android 12",
                            BatteryCapacity = 5000,
                            DisplayDiagonal = 6.8099999999999996
                        },
                        new
                        {
                            Id = "Iik7q__BtH-",
                            CategoryId = "Etn4MEcPF7H",
                            DateCreated = new DateTime(2023, 8, 5, 14, 47, 5, 37, DateTimeKind.Local).AddTicks(7908),
                            DateLastEdit = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Доооооовгий опис",
                            Dicount = 0,
                            IsDelete = false,
                            Name = "Мобільний телефон Samsung Galaxy S22",
                            Price = 45999,
                            ShortDescription = "Екран (6.1\", Dynamic AMOLED 2X, 1080x2400) / Samsung Exynos 2200 / основна квадро-камера: 50 Мп + 12 Мп + 12 Мп + 12 Мп, фронтальна камера: 10 Мп / 128 ГБ вбудованої пам'яті / 3G / LTE / 5G / GPS / Nano-SIM / Android 12",
                            BatteryCapacity = 4000,
                            DisplayDiagonal = 6.0999999999999996
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartBuyApi.DataBase.Tables.SmartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartBuyApi.DataBase.Tables.SmartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBuyApi.DataBase.Tables.SmartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartBuyApi.DataBase.Tables.SmartUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.FilterName", b =>
                {
                    b.HasOne("SmartBuyApi.Data.DataBase.Tables.CategoryEntity", "Category")
                        .WithMany("FilterNames")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.FilterValue", b =>
                {
                    b.HasOne("SmartBuyApi.Data.DataBase.Entities.FilterName", "FilterName")
                        .WithMany("Values")
                        .HasForeignKey("FilterNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterName");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.ImageEntity", b =>
                {
                    b.HasOne("SmartBuyApi.Data.DataBase.Tables.CategoryEntity", "Category")
                        .WithOne("Image")
                        .HasForeignKey("SmartBuyApi.Data.DataBase.Entities.ImageEntity", "CategoryId");

                    b.HasOne("SmartBuyApi.Data.DataBase.Entities.GlobalCategoryEntity", "GlobalCategory")
                        .WithOne("Image")
                        .HasForeignKey("SmartBuyApi.Data.DataBase.Entities.ImageEntity", "GlobalCategoryId");

                    b.HasOne("SmartBuyApi.Data.DataBase.Tables.ProductEntity", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId");

                    b.Navigation("Category");

                    b.Navigation("GlobalCategory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartBuyApi.DataBase.Tables.SmartUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SmartUserId");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.ReviewEntity", b =>
                {
                    b.HasOne("SmartBuyApi.DataBase.Tables.SmartUser", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBuyApi.Data.DataBase.Tables.ProductEntity", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Tables.CategoryEntity", b =>
                {
                    b.HasOne("SmartBuyApi.Data.DataBase.Entities.GlobalCategoryEntity", "GlobalCategory")
                        .WithMany("Categories")
                        .HasForeignKey("GlobalCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalCategory");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Tables.ProductEntity", b =>
                {
                    b.HasOne("SmartBuyApi.Data.DataBase.Tables.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartBuyApi.DataBase.Tables.Adress", b =>
                {
                    b.HasOne("SmartBuyApi.DataBase.Tables.SmartUser", "User")
                        .WithMany("Adresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.FilterName", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Entities.GlobalCategoryEntity", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Tables.CategoryEntity", b =>
                {
                    b.Navigation("FilterNames");

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartBuyApi.Data.DataBase.Tables.ProductEntity", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SmartBuyApi.DataBase.Tables.SmartUser", b =>
                {
                    b.Navigation("Adresses");

                    b.Navigation("Comments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
